### PR TITLE
Update `demo_agent/requirements.txt` to enable use of gpt-4o

### PR DESCRIPTION
**Pull request by xhluca**
- Update `demo_agent/requirements.txt` to enable use of gpt-4o
- Update `def has_vision(self):` to support 4o

With the updated requirements, you can run:

```bash
python demo_agent/run_demo.py --model_name openai/gpt-4o
```

This will enable the use of gpt-4o

### CODE REVIEW

**Comment by xhluca** [comment]
Weird, i'm getting this error when trying to use gpt-4o:

```
Traceback (most recent call last):
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/browsergym/experiments/loop.py", line 177, in run
    action = step_info.from_action(agent)
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/browsergym/experiments/loop.py", line 325, in from_action
    self.action, self.agent_info = agent.get_action(self.obs)
  File "/home/xhlu/dev/BrowserGym/demo_agent/agents/legacy/agent.py", line 131, in get_action
    ans_dict = retry(self.chat_llm, chat_messages, n_retry=self.max_retry, parser=parser)
  File "/home/xhlu/dev/BrowserGym/demo_agent/agents/legacy/utils/llm_utils.py", line 76, in retry
    answer = chat.invoke(messages)
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 248, in invoke
    self.generate_prompt(
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 677, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 534, in generate
    raise e
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 524, in generate
    self._generate_with_cache(
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 749, in _generate_with_cache
    result = self._generate(
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 543, in _generate
    response = self.client.create(messages=message_dicts, **params)
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
  File "/home/xhlu/dev/BrowserGym/venv/lib/python3.10/site-packages/openai/_base_client.py", line 1030, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid type for 'messages[1].content[1].image_url': expected an object, but got a string instead.", 'type': 'invalid_request_error', 'param': 'messages[1].content[1].image_url', 'code': 'invalid_type'}}
```

**Comment by xhluca** [comment]
Might be related: https://community.openai.com/t/image-url-for-gpt-4o-api-giving-error-expected-an-object-but-got-a-string-instead/748188/8

**Review by imenelydiaker — APPROVED** [review]
Looks really great! Thank you for adding this 🙂 

@gasse anything to add before merging?

**Review by gasse — APPROVED** [review]
LGTM

**Comment by gasse** [comment]
Thanks @xhluca @imenelydiaker !

**Pull request merged**
